repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: |
          (?x)^(
            \.git/.*|
            __pycache__/.*|
            docs/.*|
            build/.*|
            dist/.*|
            test/.*
          )$

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
            \.git/.*|
            __pycache__/.*|
            docs/.*|
            build/.*|
            dist/.*
          )$


  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: |
          (?x)^(
            \.git/.*|
            __pycache__/.*|
            docs/.*|
            build/.*|
            dist/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.940
    hooks:
      - id: mypy
        args: ['--no-warn-unused-ignores']
        additional_dependencies: ['rdflib', 'types-setuptools', 'pandas-stubs']
        exclude: |
          (?x)^(
            \.git/.*|
            test/.*|
            __pycache__/.*|
            docs/.*|
            test/.*|
            build/.*|
            scripts/.*|
            dist/.*
          )$
