# http://travis-ci.org/RDFLib/sparqlwrapper

branches:
  except:
    - gh-pages

language: python

python:
    - 3.5
    - 3.6
    - 3.7

# Enable 3.8 and 3.8-dev without globally enabling dist: xenial for other build jobs
jobs:
  include:
    - python: 3.8
      dist: focal
    - python: 3.8-dev
      env: ENV=py38-dev
      dist: focal

  allow_failures:
    - env: ENV=py38-dev

before_install:
    - pip install --upgrade pip setuptools

install:
    - python setup.py sdist && pip install ./dist/*

before_script:
    - pip install rdflib-jsonld

script: nosetests -v
