# http://travis-ci.org/RDFLib/sparqlwrapper

branches:
  except:
    - gh-pages

sudo: false

language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy

# Enable 3.7 and 3.8-dev without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      env: ENV=py38-dev
      dist: xenial
      sudo: true

  allow_failures:
    - env: ENV=py38-dev
    - python: 'pypy'

before_install:
    - pip install --upgrade pip setuptools

install:
    - python setup.py sdist && pip install ./dist/*

before_script:
    - pip install rdflib-jsonld

script: ./tests.sh 
