[build-system]
requires = ["wheel", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "--cov=SPARQLWrapper",
    "--cov-report=term-missing",
    "--durations=10", # Show 10 slowest tests durations
]
