name: Test

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        max-parallel: 1
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install '.[dev]'
    - name: Mypy
      run: |
        mypy --show-error-context --show-error-codes
    - name: Test [wrapper]
      if: ${{ always() }}
      run: |
        python -m unittest test/test_wrapper.py -v
    - name: Test [all]
      run: |
        python -m unittest -v |& tee log.txt
        grep '^FAIL:' log.txt > fails.txt
        # if all failures is not raised in `test.test_wrapper`:
        if [ "$(grep 'test.test_wrapper' fails.txt | wc -l)" -ne "$(wc -l < fails.txt)" ]; then
          exit 1
        else
          echo 'All of the above failures are maybe false errors.'
          echo 'See: https://github.com/RDFLib/sparqlwrapper/issues/192'
        fi
