name: Test

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

jobs:
  test-py35:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v2
      with:
        python-version: "3.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v

  test-py36:
    runs-on: ubuntu-latest
    if: always()
    needs: test-py35
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v

  test-py37:
    runs-on: ubuntu-latest
    if: always()
    needs: test-py36
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v

  test-py38:
    runs-on: ubuntu-latest
    if: always()
    needs: test-py37
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v

  test-py39:
    runs-on: ubuntu-latest
    if: always()
    needs: test-py38
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v

  test-py310:
    runs-on: ubuntu-latest
    if: always()
    needs: test-py39
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install nose rdflib-jsonld
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python setup.py sdist && pip install ./dist/*
    - name: Test with nosetests
      run: |
        nosetests -v
